### PR TITLE
fixes player tracking icons passing through regional gates

### LINKED ISSUE #112: Player Arrows / Username are not re-added after passing Regional Gate
While watching Turtle's stream noticed that the UI display is removed and never re-added back. 

Need to investigate to confirm.

### PR DESCRIPTION
**Pull request by 6fears7**
Closes #112 

When players are standing still to enter Regional Gate, removes the custom HUD elements. 
After everyone passes through, the elements are re-added.

### CODE REVIEW

File: Story/RainMeadow.StoryHooks.cs [hunk 1]
```diff
@@ -3,6 +3,7 @@
 using HUD;
 using System.Linq;
 using System;
+using static Sony.PS4.SaveData.Dialogs;
```
Comment (Chrometurtle) [inline Story/RainMeadow.StoryHooks.cs:6]: ?

**Review by Chrometurtle — APPROVED** [review]

File: Story/RainMeadow.StoryHooks.cs (hunk 1 above)
Comment (6fears7) [reply Story/RainMeadow.StoryHooks.cs:6]: dude I have no idea lol stupid things get added automatically.

Comment (Chrometurtle) [reply Story/RainMeadow.StoryHooks.cs:6]: happened b/c of visual studio intellesense and auto fills. Just look at the PR diff after you put it up and make the corrections.
